- platform: ffmpeg
  name: Baby Camera
  input: !secret baby_cam
- platform: ffmpeg
  name: Front Door RTSP
  input: !secret office_wyze
- platform: ffmpeg
  name: Basement RTSP
  input: !secret basement_rtsp
- platform: local_file
  file_path: /config/custom_components/mail_and_packages/mail_none.gif
  name: mail_usps