- id: '1563026077178'
  alias: Start Homekit
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - delay: 0:01
  - service: homekit.start
- id: '1568893048333'
  alias: Sunset
  trigger:
  - event: sunset
    platform: sun
  condition: []
  action:
  - brightness_pct: 100
    device_id: f27e62be9d8d4f97b8cda056b0be5211
    domain: light
    entity_id: light.streetlight
    type: turn_on
  mode: single
- id: '1568977184659'
  alias: 'Ecobee: Sleep Mode'
  trigger:
  - at: input_datetime.sleep
    platform: time
  - entity_id: binary_sensor.is_home
    platform: state
    to: 'on'
  condition:
  - after: input_datetime.sleep
    before: input_datetime.morning_start
    condition: time
  - condition: state
    entity_id: binary_sensor.is_home
    state: 'on'
  action:
  - entity_id: script.sleep_mode
    service: script.turn_on
  mode: single
- id: '1568977375898'
  alias: 'Ecobee: Home Mode'
  trigger:
  - entity_id: binary_sensor.is_home
    platform: state
    to: 'on'
  condition:
  - after: input_datetime.morning_start
    before: input_datetime.sleep
    condition: time
  - condition: state
    entity_id: binary_sensor.is_home
    state: 'on'
  action:
  - data: {}
    entity_id: script.home_mode
    service: script.turn_on
  mode: single
- id: '1568977436434'
  alias: 'Ecobee: Away Mode'
  trigger:
  - entity_id: binary_sensor.is_home
    platform: state
    to: 'off'
  condition: []
  action:
  - data: {}
    service: script.leaving_home
  mode: single
- id: '1571829369785'
  alias: Cleaning Mode
  description: ''
  trigger:
  - entity_id: lock.front_door
    from: locked
    platform: state
    to: unlocked
  condition:
  - condition: state
    entity_id: input_boolean.cleaning_mode
    state: 'on'
  action:
  - data:
      entity_id: group.all_lights
    service: light.turn_on
  - data:
      message: Denia has arrived
    service: notify.telegram_zaven
  - data:
      message: Denia has arrived
    service: notify.telegram_casey
- id: '1573778939758'
  alias: 'Matching: Kitchen Lights'
  description: Match fan lights to kitchen lights
  use_blueprint:
    path: match_lighting.yaml
    input:
      source_light: light.kitchen_lights
      target_light: light.kitchen
  mode: single
- id: '1584180828929'
  alias: 'Doors: Basement Lighting'
  description: Turn on and off the basement depending on the stairwell door
  trigger:
  - entity_id: binary_sensor.stairwell_door_contact
    platform: state
  condition: []
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: binary_sensor.stairwell_door_contact
        state: 'on'
      sequence:
      - entity_id: light.basement_stairs_lights
        service: light.turn_on
      - entity_id: light.man_cave
        service: light.turn_on
    - conditions:
      - condition: state
        entity_id: binary_sensor.stairwell_door_contact
        state: 'off'
      sequence:
      - entity_id: group.basement
        service: homeassistant.turn_off
      - entity_id: switch.surveillance_station_home_mode
        service: switch.turn_off
  mode: single
- id: '1591905462398'
  alias: 'Remote: Turn Off Basement TV'
  description: ''
  trigger:
  - device_id: 62c449cd9b29462e80b2143473c53917
    domain: hue
    platform: device
    subtype: turn_off
    type: remote_button_long_release
  condition: []
  action:
  - data: {}
    entity_id: remote.harmony
    service: remote.turn_off
  mode: single
- id: '1593732685749'
  alias: Adguard Sync
  description: ''
  trigger:
  - entity_id: switch.adguard_protection
    platform: state
  condition: []
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: switch.adguard_protection
        state: 'off'
      sequence:
      - service: pi_hole.disable
        data:
          duration: 00:00:00
    - conditions:
      - condition: state
        entity_id: switch.adguard_protection
        state: 'on'
      sequence:
      - service: pi_hole.enable
        data: {}
- id: '1596632295758'
  alias: Arrive Home
  description: ''
  trigger:
  - entity_id: person.casey
    platform: state
    to: home
  - entity_id: person.zaven
    platform: state
    to: home
  condition: []
  action:
  - service: script.unlock_house
    data: {}
  mode: single
- id: '1600221028451'
  alias: Sunrise
  description: ''
  trigger:
  - event: sunrise
    platform: sun
  condition: []
  action:
  - device_id: f27e62be9d8d4f97b8cda056b0be5211
    domain: light
    entity_id: light.streetlight
    type: turn_off
  mode: single
- id: '1604926041330'
  alias: 'Arrive Home: Casey'
  description: ''
  trigger:
  - platform: state
    entity_id: person.casey
    to: home
  condition: []
  action:
  - delay: 00:05
  - service: notify.telegram_casey
    data:
      message: Did we lock the car?
  mode: single
- id: '1610999309477'
  alias: Laundry Lights
  description: ''
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      no_motion_wait: 902
      motion_entity: binary_sensor.laundry_sensor_motion
      light_target:
        entity_id: light.laundry
- id: '1610999476218'
  alias: Leaving Work
  description: ''
  use_blueprint:
    path: homeassistant/notify_leaving_zone.yaml
    input:
      zone_entity: zone.work
      notify_device: a9f77d00cf55420aa7adc6088cc06fdc
      person_entity: person.zaven
- id: '1611233481278'
  alias: Wake Up Zaven
  description: ''
  use_blueprint:
    path: wake_up.yaml
    input:
      wake_up_time: input_datetime.wake_up_zaven
- id: '1611233498710'
  alias: Wake Up Casey
  description: ''
  use_blueprint:
    path: wake_up.yaml
    input:
      wake_up_time: input_datetime.wake_up_casey
- id: '1611234351625'
  alias: 'Match: Hallway Lighting'
  description: ''
  use_blueprint:
    path: match_lighting.yaml
    input:
      source_light: light.entrance_lights
      target_light: light.hallway
- id: '1611355660412'
  alias: 'Match: Dining Room'
  description: ''
  use_blueprint:
    path: match_lighting.yaml
    input:
      source_light:
      - light.kitchen_lights
      - light.living_room_lights
      target_light: light.dining_room
- alias: Update USPS Mail Camera Path on Hass Restart
  trigger:
  - platform: state
    entity_id: sensor.mail_updated
  - platform: homeassistant
    event: start
  action:
  - service: local_file.update_file_path
    data_template:
      entity_id: camera.mail_usps
      file_path: '{{ states(''sensor.mail_image_system_path'') }}'
  id: 16dd6f238bda4879a7453de7fa8fcdb3
- id: '1621340108636'
  alias: Freezer Check
  description: ''
  trigger:
  - platform: device
    type: turned_off
    device_id: b8dc20ca4ebb416eb507e2a549df5ac0
    entity_id: switch.freezer
    domain: switch
  condition: []
  action:
  - device_id: a9f77d00cf55420aa7adc6088cc06fdc
    domain: mobile_app
    type: notify
    title: ''
    message: The Freezer is Off
  - device_id: 261400ab5e1c4135b55792f8d7f5ba5d
    domain: mobile_app
    type: notify
    title: ''
    message: The Freezer is Off
  mode: single
