- id: '1563026077178'
  alias: Start Homekit
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - delay: 0:01
  - service: homekit.start
- id: '1593732685749'
  alias: Adguard Sync
  description: ''
  trigger:
  - entity_id: switch.adguard_protection
    platform: state
  condition: []
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: switch.adguard_protection
        state: 'off'
      sequence:
      - service: pi_hole.disable
        data:
          duration: 00:00:00
    - conditions:
      - condition: state
        entity_id: switch.adguard_protection
        state: 'on'
      sequence:
      - service: pi_hole.enable
        data: {}
- id: '1596632295758'
  alias: Arrive Home
  description: ''
  trigger:
  - entity_id: person.casey
    platform: state
    to: home
    id: casey_home
  - platform: device
    device_id: 261400ab5e1c4135b55792f8d7f5ba5d
    domain: device_tracker
    entity_id: device_tracker.zaven_iphone
    type: enters
    id: zaven_home
    zone: zone.home
  condition: []
  action:
  - service: script.unlock_house
    data: {}
  - condition: trigger
    id: casey_home
  - delay: 00:05
  - device_id: a9f77d00cf55420aa7adc6088cc06fdc
    domain: mobile_app
    type: notify
    title: ''
    message: Did we lock the car?
  mode: single
- id: '1600221028451'
  alias: Sun Changes
  description: ''
  trigger:
  - event: sunrise
    platform: sun
    id: sunrise
  - platform: sun
    event: sunset
    id: sunset
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id: sunrise
      sequence:
      - service: light.turn_off
        target:
          entity_id: light.streetlights
    - conditions:
      - condition: trigger
        id: sunset
      sequence:
      - service: light.turn_on
        target:
          entity_id: light.streetlights
    default: []
  mode: single
- id: '1610999476218'
  alias: Leaving Work
  description: ''
  use_blueprint:
    path: homeassistant/notify_leaving_zone.yaml
    input:
      zone_entity: zone.work
      notify_device: a9f77d00cf55420aa7adc6088cc06fdc
      person_entity: person.zaven
- id: '1611233481278'
  alias: Wake Up Zaven
  description: ''
  use_blueprint:
    path: wake_up.yaml
    input:
      wake_up_time: input_datetime.wake_up_zaven
- id: '1611233498710'
  alias: Wake Up Casey
  description: ''
  use_blueprint:
    path: wake_up.yaml
    input:
      wake_up_time: input_datetime.wake_up_casey
- alias: Update USPS Mail Camera Path on Hass Restart
  trigger:
  - platform: state
    entity_id: sensor.mail_updated
  - platform: homeassistant
    event: start
  action:
  - service: local_file.update_file_path
    data_template:
      entity_id: camera.mail_usps
      file_path: '{{ states(''sensor.mail_image_system_path'') }}'
  id: 16dd6f238bda4879a7453de7fa8fcdb3
- id: '1624832277642'
  alias: Nursery Music Loop
  description: ''
  trigger:
  - platform: device
    device_id: ce8fe1ee4b9f4c2a84629930787765f3
    domain: media_player
    entity_id: media_player.nursery_speaker
    type: idle
  - platform: device
    device_id: ce8fe1ee4b9f4c2a84629930787765f3
    domain: media_player
    entity_id: media_player.nursery_speaker
    type: paused
  - platform: device
    device_id: ce8fe1ee4b9f4c2a84629930787765f3
    domain: media_player
    entity_id: media_player.nursery_speaker
    type: turned_off
  condition:
  - condition: state
    entity_id: switch.white_noise
    state: 'on'
  action:
  - service: media_player.play_media
    entity_id: media_player.nursery_speaker
    data:
      media_content_id: http://www.gstatic.com/voice_delight/sounds/long/ocean.mp3
      media_content_type: url
  mode: single
- id: '1624832716801'
  alias: Nursery Music Toggle
  description: ''
  trigger:
  - device_id: 77978197a7c443bdbae39c657f196340
    domain: hue
    platform: device
    type: remote_button_long_release
    subtype: dim_down
  condition: []
  action:
  - service: switch.toggle
    target:
      entity_id: switch.white_noise
  mode: single
- id: '1625754961035'
  alias: Nursery Sleeping
  description: ''
  trigger:
  - platform: state
    entity_id: switch.white_noise
  condition: []
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: switch.white_noise
        state: 'on'
      sequence:
      - device_id: 8938d322fd3b11eab38eafa121ce86b4
        domain: climate
        entity_id: climate.ecobee
        type: set_preset_mode
        preset_mode: Sleep
      - type: turn_on
        device_id: dbc45aa30675419796d297f37482837f
        entity_id: switch.nursery_room_fan
        domain: switch
    - conditions:
      - condition: state
        entity_id: switch.white_noise
        state: 'off'
      sequence:
      - service: ecobee.resume_program
        data:
          resume_all: true
      - condition: state
        entity_id: binary_sensor.nursery_occupancy
        state: 'off'
      - type: turn_off
        device_id: dbc45aa30675419796d297f37482837f
        entity_id: switch.nursery_room_fan
        domain: switch
    default: []
  mode: single
- id: '1626091307899'
  alias: Comfort Settings
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.is_home
    id: home
    to: 'on'
  - platform: time
    at: input_datetime.sleep
    id: sleep
  - platform: state
    entity_id: binary_sensor.is_home
    id: away
    to: 'off'
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id: home
      sequence:
      - service: script.home_mode
    - conditions:
      - condition: trigger
        id: away
      sequence:
      - service: script.leaving_home
    - conditions:
      - condition: trigger
        id: sleep
      - condition: state
        entity_id: binary_sensor.is_home
        state: 'on'
      sequence:
      - service: script.sleep_mode
    default: []
  mode: single
- id: '1629989041599'
  alias: Vacuum House
  description: ''
  trigger:
  - platform: time
    at: input_datetime.vacuum
  condition:
  - condition: state
    entity_id: binary_sensor.is_home
    state: 'on'
  action:
  - device_id: 993acbd32f40399e3ddc79cb1b168bca
    domain: vacuum
    entity_id: vacuum.roborock_s4
    type: clean
  mode: single
- id: '1635208283021'
  alias: Water Detected
  description: ''
  trigger:
  - type: moist
    platform: device
    device_id: e2641cdbd4220be3c6f49ee00162c487
    entity_id: binary_sensor.water_heater_leak_leak
    domain: binary_sensor
  - type: moist
    platform: device
    device_id: ae7403119e0b26dbc8d89c880db18f5c
    entity_id: binary_sensor.sump_pit_water
    domain: binary_sensor
  - device_id: 6a38d6efa5ccd0b9f976bd91d1ca188c
    domain: zha
    platform: device
    type: device_offline
    subtype: device_offline
  condition: []
  action:
  - device_id: 261400ab5e1c4135b55792f8d7f5ba5d
    domain: mobile_app
    type: notify
    title: ''
    message: Water Detected
  - device_id: a9f77d00cf55420aa7adc6088cc06fdc
    domain: mobile_app
    type: notify
    title: ''
    message: Water detected
  - service: notify.telegram_zaven
    data:
      message: Water Detected
  mode: single
