
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
homeassistant:
  customize: !include customize.yaml
  
frontend:
  themes: !include_dir_merge_named themes
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.2.10
# Text to speech
tts:
  - platform: google_translate

# Homeassistant Configs
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
zone: !include zone.yaml

# Entities
sensor: !include entities/sensors.yaml
binary_sensor: !include entities/binary_sensors.yaml
switch: !include entities/switches.yaml
light: !include entities/light.yaml
remote: !include entities/remote.yaml
  
# Integrations
camera: !include integrations/camera.yaml
climate: !include_dir_list integrations/climate
hue: !include integrations/hue.yaml
lutron_caseta: !include integrations/lutron.yaml
tplink: !include integrations/tplink.yaml
ifttt: !include integrations/ifttt.yaml
spotify: !include integrations/spotify.yaml

# Assistants
# homekit: !include assistants/homekit.yaml
google_assistant: !include assistants/google_assistant.yaml
emulated_hue: !include assistants/emulated_hue.yaml  

# Notifications
telegram_bot: !include notifications/telegram.yaml
notify: !include notifications/notify.yaml
