- platform: group
  name: Office
  entities:
  - light.office_lamp
  - light.office_left
  - light.office_right
- platform: group
  name: Bathroom
  entities:
  - light.bathroom_1
  - light.bathroom_2
  - light.bathroom_3