- platform: group
  name: Bathroom
  entities:
  - light.bathroom_1
  - light.bathroom_2
  - light.bathroom_3
- platform: group
  name: Bedroom Lamp
  entities:
    - light.bedroom_lamp_1
    - light.bedroom_lamp_2
    - light.bedroom_lamp_3