- platform: waze_travel_time
  name: School
  origin: device_tracker.caseys_iphone
  destination: !secret school_addr
  region: 'US'
- platform: waze_travel_time
  name: Work
  origin: device_tracker.zaven_phone
  destination: !secret work_addr
  region: 'US'
- platform: waze_travel_time
  name: Casey ETA
  origin: device_tracker.caseys_iphone
  destination: !secret home_addr
  region: 'US'
- platform: waze_travel_time
  name: Zaven ETA
  origin: device_tracker.zaven_phone
  destination: !secret home_addr
  region: 'US'
- platform: cert_expiry
  host: !secret domain
- platform: synologydsm
  host: !secret syno_ip
  username: !secret syno_user
  password: !secret syno_password
  monitored_conditions:
  - cpu_total_load
  - memory_real_usage
  - network_up